name: iOS starter workflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build iPhone 16
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: .build/packages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        run: |
          scheme=$(cat default)
          
          
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then 
            filetype_parameter="workspace"
            file_to_build="`ls -A | grep -i \\.xcworkspace\$ | head -1`"
          else 
            filetype_parameter="project"
            file_to_build="`ls -A | grep -i \\.xcodeproj\$ | head -1`"
          fi
          
          
          DESTINATION="platform=iOS Simulator,name=iPhone 16"
          
          echo "Building $scheme for $DESTINATION..."
          
          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" \
          -destination "$DESTINATION" \
          -clonedSourcePackagesDirPath .build/packages \
          CODE_SIGNING_ALLOWED=NO
