name: iOS starter workflow

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build iPhone 16 (iOS 18.4)
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default > default
          echo "Using default scheme: $default"

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: 'iOS Simulator'
          device: 'iPhone 16'
          os: '18.4'
        run: |
          if [ $scheme = default ]; then scheme=$(cat default); fi
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          
          xcodebuild build -scheme "$scheme" -"$filetype_parameter" "$file_to_build" \
          -destination "platform=$platform,name=$device,OS=$os" \
          CODE_SIGNING_ALLOWED=NO
