name: iOS starter workflow

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: .build/packages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build (Simulator SDK)
        run: |
          set -e

          xcodebuild build \
            -project CampusCare.xcodeproj \
            -scheme CampusCare \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -clonedSourcePackagesDirPath .build/packages \
            CODE_SIGNING_ALLOWED=NO
